Adding sitemap index to the root file
vtex-apps/store-locator pull request #15
Opened 2020-12-04 16:57 UTC by wender

#### What problem is this solving?
Make a list of stores available to the Search Engines

#### How to test it?

[Workspace](https://sitemap--sandboxusdev.myvtex.com/sitemap.xml)

#### Screenshots or example usage:
![image](https://user-images.githubusercontent.com/24723/101191547-902f0080-3638-11eb-981e-fa537a2e6201.png)

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-12-04 18:28 UTC, SDBowen approved these changes

2020-12-07 12:41 UTC, guerreirobeatriz requested changes

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +| `store-instructions` |                    Renders the desired instructions to access the retail store.                    |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +| `iconHeight`  | `number` |                           Icon height in pixels (`px`).                           | Image default height. |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +| `phoneSelector` | `string` |                             CSS Selector that will wrap all the phone numbers displayed on the UI.                             |  `undefined`  |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +|   `tag`   | `string` |                              HTML element to wrap the `store-name` block when rendered on the UI.                              |     `div`     |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +|  `label`  | `string` | Entitles the `store-back-link` block when rendered on the UI. | `Back to all stores` |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +| `height`  | `string` | Map height in pixels (`px`). |    `200px`    |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +|  `label`  | `string` | Entitles the `store-address` block when rendered on the UI. | `Store address` |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +| `format`  |  `enum`  |    Hour format. Possible values are : `12h` and `24h`.    |     `24h`      |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +|  `label`  | `string` | Entitles the `store-instructions` block when rendered on the UI. | `Information` |
No need to add the extra space :) The former version is better to read and edit the file, and it works just fine once rendered!

2020-12-07 12:41 UTC, guerreirobeatriz commented on docs/README.md
> +Make sure you have the `vtex.store-sitemap@2.x` App installed on your account to make use of the sitemap feature.
```suggestion
> ℹ️ *This app will also **add a new entry to your store's `/sitemap.xml` file in order to have all the pickup points available to the search engines** - make sure you already have the `vtex.store-sitemap@2.x` app installed in your VTEX account!*
```

2020-12-16 15:43 UTC, merged