[STORELOCAT-25] Holiday exception hours updated
vtex-apps/store-locator pull request #54
Opened 2022-07-01 17:24 UTC by albertm805

#### What problem is this solving?
- The store locator currently doesn't show any exception of hours or if is closed
- This was added in a separate section bellow the business hours

#### How to test it?
- You can test by visiting [this](https://beto--productusqa.myvtex.com/store/mexico-pickup-point-ciudad-de-mexico-03580/Mexico1) workspace

#### Screenshots or example usage:
![Image 2022-07-01 at 12 21 26 p m](https://user-images.githubusercontent.com/11176519/176941539-a2962179-c992-4a14-8bd8-6700c36ce0ac.jpg)

#### Image description
- The image shows only one holiday but there are 3 exception hours/holidays added
- One is that there are past holiday exceptions
- Another is that there is a valida holiday but without open and closing time (This will be set to closed)
- If there are business hours in this holiday then the hours will be set.

2022-07-01 17:37 UTC, polishq commented
Instead of `Friday, 1`, can it say `Friday, July 1` (or whatever the month is)?

2022-07-01 18:04 UTC, Arturo777 requested changes

2022-07-01 18:04 UTC, Arturo777 commented on react/queries/getStore.gql
> +    }
vtex.store-graphql already have this fields? if not, this app will break the store details

2022-07-01 18:06 UTC, albertm805 commented on react/StoreHours.tsx
> +    const dayOfMonth = holiday.getDate()
Already did that.

2022-07-01 18:07 UTC, Arturo777 requested changes

2022-07-01 18:07 UTC, Arturo777 commented on react/queries/getStore.gql
> +    }
vtex.store-graphql already have this fields in the getStore query? if not, this app will break the store details, maybe we have to wait for it before publish this version.

2022-07-06 15:22 UTC, Arturo777 approved these changes
LGTM

2022-08-09 17:35 UTC, polishq approved these changes
LGTM

2022-08-09 20:59 UTC, merged